data_dir: src/image_captioning_system/data/flickr8k
images_dir: src/image_captioning_system/data/flickr8k/Images
captions_path: src/image_captioning_system/data/flickr8k/captions.txt

split:
  test_size: 0.15
  val_size: 0.1
  random_state: 42